# Question 1


In [3]:
import numpy as np
array = np.arange(2,51,3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2

In [9]:
array_1 = list(map(int, input().split(" ")))
array_2 = list(map(int, input().split(" ")))
numpy_array_1 = np.array(array_1)
numpy_array_2 = np.array(array_2)
final_array = np.concatenate((numpy_array_1, numpy_array_2))
final_array.sort()
final_array

0 2 4 6
1 3 5 7


array([0, 1, 2, 3, 4, 5, 6, 7])

# Question 3

In [15]:
array_new = np.array([1, 3, 5, 7])
dimension = array_new.ndim
size = array_new.size
print(f"dimension is {dimension}, size is {size}")

dimension is 1, size is 4


# Question 4

In [21]:
array_first = np.array([1, 2, 3, 4])# initial array
array_first.shape # this gives shape as 1 which is 1D
convert = array_first[np.newaxis,: ] # converts into 2D array
cconvert.shape # this gives shape as  (1,4) which is 2D
print(convert)

[[1 2 3 4]]


# Question 5

In [32]:
array_one = np.array([[1, 2], [3, 4]])
array_two = np.array([[5, 6], [7, 8]])
first = np.hstack((array_one, array_two))
print("Horizontally Stacked")
print(first)

Horizontally Stacked
[[1 2 5 6]
 [3 4 7 8]]


In [33]:
second = np.vstack((array_one, array_two))
print("Vertically Stacked")
print(second)

Vertically Stacked
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Question 6

In [34]:
last_array = [1, 2, 1, 2, 2, 3]
unique, count = np.unique(last_array, return_counts=True)
print(f"The unique elements are {unique} and the count is {count}")

The unique elements are [1 2 3] and the count is [2 3 1]
